version: '3.7'

services:
  backend:
    image: ecommerce_app
    build:
      context: .
    volumes:
      - static_data:/backend/staticfiles
    env_file: # if .env in root, we have to show .env here must
      - ./.env

  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/backend/staticfiles
    ports:
      - "8000:8000"
    env_file: # if .env in root, we have to show .env here must
      - ./.env
    depends_on:
      - backend
volumes:
  static_data:
